# Generated by Django 5.2.9 on 2026-03-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Epoca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Época')),
                ('inicio_data', models.DateField(blank=True, null=True, verbose_name='Início')),
                ('fim_data', models.DateField(blank=True, null=True, verbose_name='Fim')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Época',
                'verbose_name_plural': 'Épocas',
                'ordering': ['-criado_em', 'nome'],
            },
        ),
    ]
