# Generated by Django 5.2.9 on 2026-03-25 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associacao', '0004_associacao_complemento_associacao_numero'),
        ('core', '0003_modalidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpocaAssociacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('associacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epocas', to='associacao.associacao')),
                ('epoca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associacoes_epoca', to='core.epoca')),
            ],
            options={
                'verbose_name': 'Associação na Época',
                'verbose_name_plural': 'Associações nas Épocas',
                'ordering': ['-criado_em'],
                'unique_together': {('epoca', 'associacao')},
            },
        ),
    ]
