# Generated by Django 5.2.9 on 2026-03-25 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitro', '0006_remove_arbitro_especialidade_arbitro_modalidade'),
        ('core', '0004_epocaassociacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpocaArbitro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('arbitro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epocas', to='arbitro.arbitro')),
                ('epoca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arbitros_epoca', to='core.epoca')),
            ],
            options={
                'verbose_name': 'Árbitro na Época',
                'verbose_name_plural': 'Árbitros nas Épocas',
                'ordering': ['-criado_em'],
                'unique_together': {('epoca', 'arbitro')},
            },
        ),
    ]
