# Generated by Django 5.2.9 on 2026-04-08 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_epocaarbitro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forcar_troca_password', models.BooleanField(default=False, verbose_name='Obrigar troca de palavra-passe no próximo acesso')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_conta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de conta',
                'verbose_name_plural': 'Perfis de conta',
            },
        ),
    ]
