# Generated by Django 5.2.9 on 2026-04-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_perfil_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilconta',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='perfil/avatar/', verbose_name='Foto de perfil'),
        ),
    ]
