# Generated by Django 5.2.9 on 2026-04-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_perfil_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilconta',
            name='departamento',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Departamento'),
        ),
    ]
