# Generated by Django 5.2.9 on 2026-03-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exame',
            options={'ordering': ['nome'], 'verbose_name': 'Ato Médico', 'verbose_name_plural': 'Atos Médicos'},
        ),
        migrations.AlterField(
            model_name='exame',
            name='nome',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nome do Ato Médico'),
        ),
    ]
