# Generated by Django 5.2.9 on 2026-04-07 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitro', '0007_arbitro_uniq_arbitro_cpf_nif_not_empty'),
        ('associacao', '0004_associacao_complemento_associacao_numero'),
        ('core', '0005_epocaarbitro'),
        ('exames', '0002_alter_exame_options_alter_exame_nome'),
        ('prestador', '0002_prestadorexamevalor'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcacaoExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Marcado em')),
                ('arbitro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcacoes_exames', to='arbitro.arbitro')),
                ('associacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcacoes_exames', to='associacao.associacao')),
                ('epoca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcacoes_exames', to='core.epoca')),
                ('prestador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marcacoes_exames', to='prestador.prestador')),
            ],
            options={
                'verbose_name': 'Marcação de Exame',
                'verbose_name_plural': 'Marcações de Exames',
                'ordering': ['-criado_em'],
                'constraints': [models.UniqueConstraint(fields=('epoca', 'arbitro'), name='uniq_marcacao_epoca_arbitro')],
            },
        ),
    ]
