# Generated by Django 5.2.9 on 2026-04-07 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0003_marcacaoexame'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcacaoexame',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.CreateModel(
            name='MarcacaoExameItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exame_nome', models.CharField(max_length=255, verbose_name='Exame')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('marcacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='exames.marcacaoexame')),
            ],
            options={
                'verbose_name': 'Exame da Marcação',
                'verbose_name_plural': 'Exames da Marcação',
                'ordering': ['exame_nome'],
            },
        ),
    ]
