# Generated by Django 5.2.9 on 2026-04-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0004_marcacaoexame_observacao_marcacaoexameitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcacaoexame',
            name='data_hora_consulta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e hora da consulta'),
        ),
    ]
