# Generated by Django 6.0.1 on 2026-05-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0005_marcacaoexame_data_hora_consulta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exame',
            options={'ordering': ['codigo', 'nome'], 'verbose_name': 'Ato Médico', 'verbose_name_plural': 'Atos Médicos'},
        ),
        migrations.AddField(
            model_name='exame',
            name='abreviatura',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Abreviatura'),
        ),
        migrations.AddField(
            model_name='exame',
            name='codigo',
            field=models.PositiveIntegerField(blank=True, help_text='Código numérico do ato (ex.: 100).', null=True, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='nome',
            field=models.CharField(max_length=255, unique=True, verbose_name='Descritivo'),
        ),
    ]
