# Generated by Django 5.2.9 on 2026-03-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associacao',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='associacao',
            name='nome',
        ),
        migrations.AddField(
            model_name='associacao',
            name='avenca',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Avença'),
        ),
        migrations.AddField(
            model_name='associacao',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal'),
        ),
        migrations.AddField(
            model_name='associacao',
            name='concelho',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Concelho'),
        ),
        migrations.AddField(
            model_name='associacao',
            name='conformidade',
            field=models.CharField(blank=True, choices=[('', '--------'), ('conforme', 'Conforme'), ('nao_conforme', 'Não Conforme')], max_length=32, null=True, verbose_name='Conformidade'),
        ),
        migrations.AddField(
            model_name='associacao',
            name='distrito',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Distrito'),
        ),
        migrations.AddField(
            model_name='associacao',
            name='estado',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('em_negociacao', 'Em negociação'), ('negociacao_sem_sucesso', 'Negociação sem sucesso')], default='ativo', max_length=32),
        ),
        migrations.AddField(
            model_name='associacao',
            name='fax',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fax'),
        ),
        migrations.AddField(
            model_name='associacao',
            name='fim_protocolo_data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='associacao',
            name='fim_protocolo_hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='associacao',
            name='inicio_protocolo_data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='associacao',
            name='inicio_protocolo_hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='associacao',
            name='localidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Localidade'),
        ),
        migrations.AddField(
            model_name='associacao',
            name='nif',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='NIF'),
        ),
        migrations.AddField(
            model_name='associacao',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Completo'),
        ),
        migrations.AddField(
            model_name='associacao',
            name='responsavel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='associacao',
            name='rua_avenida',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Rua / Avenida'),
        ),
        migrations.AlterField(
            model_name='associacao',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='associacao',
            name='telefone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefone'),
        ),
    ]
