# Generated by Django 5.2.9 on 2026-03-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associacao', '0003_remove_associacao_avenca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='associacao',
            name='complemento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='associacao',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número da Porta'),
        ),
    ]
