# Generated by Django 6.0.1 on 2026-03-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('nif', models.CharField(max_length=9)),
                ('inicio_protocolo_data', models.DateField(blank=True, null=True)),
                ('inicio_protocolo_hora', models.TimeField(blank=True, null=True)),
                ('fim_protocolo_data', models.DateField(blank=True, null=True)),
                ('fim_protocolo_hora', models.TimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('em_negociacao', 'Em negociação'), ('negociacao_sem_sucesso', 'Negociação sem sucesso')], default='ativo', max_length=32)),
                ('codigo_postal', models.CharField(blank=True, max_length=10)),
                ('localidade', models.CharField(blank=True, max_length=100)),
                ('concelho', models.CharField(blank=True, max_length=100)),
                ('distrito', models.CharField(blank=True, max_length=100)),
                ('rua_avenida', models.CharField(blank=True, max_length=255)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('observacoes_morada', models.TextField(blank=True)),
                ('responsavel', models.CharField(blank=True, max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('fax', models.CharField(blank=True, max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Prestador',
                'verbose_name_plural': 'Prestadores',
            },
        ),
    ]
