# Generated by Django 5.2.9 on 2026-03-23 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestadorExameValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exame_nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Exame')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exames_valores', to='prestador.prestador')),
            ],
            options={
                'verbose_name': 'Exame e Valor',
                'verbose_name_plural': 'Exames e Valores',
            },
        ),
    ]
