# Generated by Django 5.2.9 on 2026-03-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbitro',
            name='associacao_futebol',
            field=models.CharField(blank=True, max_length=100, verbose_name='Associação de futebol'),
        ),
        migrations.AddField(
            model_name='arbitro',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='arbitro',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=20, verbose_name='Código postal'),
        ),
        migrations.AddField(
            model_name='arbitro',
            name='cpf_nif',
            field=models.CharField(blank=True, max_length=50, verbose_name='CPF / NIF'),
        ),
        migrations.AddField(
            model_name='arbitro',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AddField(
            model_name='arbitro',
            name='data_ultimo_exame',
            field=models.DateField(blank=True, null=True, verbose_name='Data do último exame médico'),
        ),
        migrations.AddField(
            model_name='arbitro',
            name='especialidade',
            field=models.CharField(blank=True, max_length=50, verbose_name='Especialidade'),
        ),
        migrations.AddField(
            model_name='arbitro',
            name='morada',
            field=models.CharField(blank=True, max_length=255, verbose_name='Morada'),
        ),
        migrations.AddField(
            model_name='arbitro',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='arbitro',
            name='telefone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telemóvel'),
        ),
        migrations.AlterField(
            model_name='arbitro',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
    ]
