# Generated by Django 5.2.9 on 2026-03-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitro', '0002_arbitro_associacao_futebol_arbitro_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbitro',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='arbitro',
            name='localidade',
            field=models.CharField(blank=True, max_length=100, verbose_name='Localidade'),
        ),
        migrations.AddField(
            model_name='arbitro',
            name='numero',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='arbitro',
            name='observacoes_morada',
            field=models.TextField(blank=True, verbose_name='Observações da morada'),
        ),
        migrations.AddField(
            model_name='arbitro',
            name='rua_avenida',
            field=models.CharField(blank=True, max_length=255, verbose_name='Rua / Avenida'),
        ),
        migrations.AlterField(
            model_name='arbitro',
            name='cpf_nif',
            field=models.CharField(blank=True, max_length=9, verbose_name='NIF'),
        ),
    ]
