# Generated by Django 5.2.9 on 2026-03-25 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitro', '0003_arbitro_complemento_arbitro_localidade_and_more'),
        ('core', '0002_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitro',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arbitros', to='core.categoria'),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
