# Generated by Django 5.2.9 on 2026-03-25 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitro', '0004_alter_arbitro_categoria_delete_categoria'),
        ('associacao', '0004_associacao_complemento_associacao_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitro',
            name='associacao_futebol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arbitros', to='associacao.associacao', verbose_name='Associação de futebol'),
        ),
    ]
