# Generated by Django 5.2.9 on 2026-03-25 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitro', '0005_alter_arbitro_associacao_futebol'),
        ('core', '0003_modalidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arbitro',
            name='especialidade',
        ),
        migrations.AddField(
            model_name='arbitro',
            name='modalidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arbitros', to='core.modalidade', verbose_name='Modalidade'),
        ),
    ]
