# Generated by Django 5.2.9 on 2026-03-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitro', '0006_remove_arbitro_especialidade_arbitro_modalidade'),
        ('associacao', '0004_associacao_complemento_associacao_numero'),
        ('core', '0005_epocaarbitro'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='arbitro',
            constraint=models.UniqueConstraint(condition=models.Q(('cpf_nif', ''), _negated=True), fields=('cpf_nif',), name='uniq_arbitro_cpf_nif_not_empty'),
        ),
    ]
