# Generated by Django 5.2.9 on 2026-04-07 11:57

import django.db.models.deletion
from django.db import migrations, models


def forwards_estado_desde_ativo(apps, schema_editor):
    Arbitro = apps.get_model("arbitro", "Arbitro")
    Arbitro.objects.filter(ativo=False).update(estado_aptidao="inativo")


def backwards_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('arbitro', '0007_arbitro_uniq_arbitro_cpf_nif_not_empty'),
        ('prestador', '0002_prestadorexamevalor'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbitro',
            name='estado_aptidao',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('aguardando_exame', 'Aguardando o exame')], default='ativo', max_length=32, verbose_name='Situação de aptidão'),
        ),
        migrations.RunPython(forwards_estado_desde_ativo, backwards_noop),
        migrations.CreateModel(
            name='RealizacaoExameArbitro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_realizacao', models.DateField(verbose_name='Data da realização')),
                ('exames_complementares', models.TextField(blank=True, verbose_name='Exames complementares')),
                ('data_marcacao_complementar', models.DateTimeField(blank=True, null=True, verbose_name='Data marcada para exame complementar')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('arbitro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realizacoes_exame', to='arbitro.arbitro')),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='realizacoes_exame_arbitro', to='prestador.prestador')),
            ],
            options={
                'verbose_name': 'Realização de exame (árbitro)',
                'verbose_name_plural': 'Realizações de exame (árbitros)',
                'ordering': ['-criado_em'],
            },
        ),
    ]
