# Generated by Django 5.2.9 on 2026-04-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitro', '0008_estado_aptidao_realizacao_exame'),
    ]

    operations = [
        migrations.AddField(
            model_name='realizacaoexamearbitro',
            name='arquivo_exame',
            field=models.FileField(blank=True, upload_to='exames/arbitros/', verbose_name='Ficheiro do exame'),
        ),
    ]
